apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: adelaide-weather
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: adelaide-weather
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: api
  sessionAffinity: None